version: "2"
services:
  node:
    image: "node"
    user: "node"
    restart: always
    working_dir: /home/snc-node-bridge
    environment:
      - NODE_ENV=production
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    links:
      - "chrome"
    volumes:
      - ./servicenow-node-bridge:/home/snc-node-bridge
    command: "yarn start"
  rest-web:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    links:
      - "chrome"
    ports:
      - "8080:8080"
  chrome:
    image: zenika/alpine-chrome:latest
    command: --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
    ports:
      - "9222:9222"
    networks:
      static-network:
        ipv4_address: 172.20.128.4
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16